version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: poolcamera
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  ffmpeg:
    image: jrottenberg/ffmpeg
    command: >
      -i rtsp://<camera_ip>:554/h264Preview_01_main
      -f hls -hls_time 2 -hls_list_size 10
      /var/www/html/public/stream.m3u8
    volumes:
      - ./public:/var/www/html/public

  shelly-webhook:
    image: python:3.10-slim
    volumes:
      - ./scripts:/app
    command: python /app/shelly_listener.py
