version: '3'

services:
  clipmanager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT}:${PORT:-5000}"
    volumes:
      - ./clips:/app/clips
    restart: unless-stopped
