services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clipmanager-app
    volumes:
      - ./app:/var/www
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=clipmanager
      - DB_USERNAME=root
      - DB_PASSWORD=root

  db:
    image: mysql:8.0
    container_name: clipmanager-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clipmanager
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: clipmanager-nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  dbdata: